name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

env:
  GO_VERSION: '1.25.x'
  GOLANGCI_LINT_VERSION: v2.7

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    container: golang:1.24

    steps:
      - uses: actions/checkout@v4

      - name: Fix git safe directory
        uses: ./.github/actions/fix-git-safe-directory

      - name: Build and lint
        uses: ./.github/actions/build-and-lint
        with:
          GO_VERSION: ${{ env.GO_VERSION }}
          GOLANGCI_LINT_VERSION: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Run all tests
        run: |
          go test ./... -v -count=1

  run-on-petclinic-without-installed-java-17:
    runs-on: ubuntu-latest
    container: golang:1.25

    steps:
      - uses: actions/checkout@v4

      - name: Setup seqra
        uses: ./.github/actions/setup-seqra
        with:
          go-version: '1.25.x'

      - name: Set GitHub token arg
        id: github-token
        run: |
          TOKEN_ARG=""
          if [ -n "${{ secrets.SEQRA_GITHUB_TOKEN }}" ]; then
            TOKEN_ARG="--github-token ${{ secrets.SEQRA_GITHUB_TOKEN }}"
          fi
          echo "arg=$TOKEN_ARG" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-petclinic
          path: project-root-java-11
          ref: a5cbb8505a1df3c348c06607933a07fc8c87c222
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run seqra scan in native environment when user can build project but has no java 17+
        run: |
          ./seqra scan ${{ steps.github-token.outputs.arg }} --output report.sarif project-root-java-11 --verbosity debug

  run-on-petclinic:
    runs-on: ubuntu-latest
    container: golang:1.24

    steps:
      - uses: actions/checkout@v4

      - name: Setup seqra
        uses: ./.github/actions/setup-seqra

      - name: Set GitHub token arg
        id: github-token
        run: |
          TOKEN_ARG=""
          if [ -n "${{ secrets.SEQRA_GITHUB_TOKEN }}" ]; then
            TOKEN_ARG="--github-token ${{ secrets.SEQRA_GITHUB_TOKEN }}"
          fi
          echo "arg=$TOKEN_ARG" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-petclinic
          path: project-root
          ref: 30aab0ae764ad845b5eedd76028756835fec771f
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run seqra separate compile and scan
        run: |
          ./seqra compile --quiet ${{ steps.github-token.outputs.arg }} --output portable-project project-root --verbosity debug
          ./seqra scan --quiet ${{ steps.github-token.outputs.arg }} --output report.sarif portable-project --verbosity debug

      - name: Run seqra scan
        run: |
          ./seqra scan --quiet ${{ steps.github-token.outputs.arg }} --output report.sarif project-root
