name: Release

on:
  push:
    branches:
      - main
      - 'release/**'
env:
  SEQRA_DEPENDENCIES_VERSION: 

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container: ghcr.io/catthehacker/ubuntu:act-latest
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: 'Install and Configure applications'
        run: |
          apt-get update
          apt-get install -yqq --no-install-recommends \
            nodejs \
            npm
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Workaround for escape error `fatal: detected dubious ownership in repository at`
      # https://github.com/actions/checkout/issues/1048#issuecomment-2768908874
      -
        name: Fix repo for release
        run: |
          git status || git config --global --add safe.directory $GITHUB_WORKSPACE
      -
        name: 'Release'
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 23.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@7.0.2
      -
        name: 'Get release_version and pass to next job'
        id: release_version
        # see .releaserc.json to obtain certain file name
        run: |
          if [ -f release_version.txt ]; then
            echo "status=succeeded" >>"$GITHUB_OUTPUT"
            echo "RELEASE_VERSION=$(cat release_version.txt)" >> $GITHUB_OUTPUT
          else
            echo "status=skipped" >>"$GITHUB_OUTPUT"
          fi
          rm -f release_version.txt
      -
        name: Login to GitHub Container Registry
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          password: ${{ secrets.SEQRA_GITHUB_TOKEN }}
      -
        name: Set up QEMU
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: docker/setup-buildx-action@v3
      -
        name: Set up Go
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.0'
      -
        name: Docker meta
        id: meta
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.release_version.outputs.RELEASE_VERSION }}
      -
        name: Run GoReleaser
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        if: ${{ steps.release_version.outputs.status == 'succeeded' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          build-contexts: |
            seqra-dependencies:latest=docker-image://ghcr.io/${{ github.repository_owner }}/seqra-infra-dependencies/seqra-dependencies:${{ env.SEQRA_DEPENDENCIES_VERSION }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            github_token=${{ secrets.SEQRA_GITHUB_TOKEN }}
          build-args: |
            SEQRA_BUILD_FLAGS=-s -w -X github.com/seqra/seqra/v2/internal/version.Version=${{ steps.release_version.outputs.RELEASE_VERSION }}

    outputs:
      release_version: ${{ steps.release_version.outputs.RELEASE_VERSION }}
